cxf:
  path: /api
  endpoint-address: /integratedPeopleManagement/v1
  jaxrs:
    client:
      address: http://127.0.0.1:4443
      classes-scan-packages: ngfs.integratedpeoplemanagement.houseservice
spring:
  application:
    name: integrated-people-management
  datasource:
    url: jdbc:postgresql://localhost:5555/test
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      javax:
        persistence:
          validation:
            group:
              pre-remove: javax.validation.groups.Default
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        delimiter: ;


logging:
  level:
    root: INFO